// -----------------------------BROWSER CONTEXT API------------------
/*
    Browser Context Api
        |-> Window
            |-> Contains elements that are not the part of Js, but can be used(accessed) by it.

        |-> Stack
            |-> Added element(same concept as in data structures,FIFO)

        |-> Heap Memory
            |->All the variables created needed to be stored somewhere that is stored in heap memory

*/